/**
 * Guest Report Page
 * Public report viewing via share token
 */

import { useParams } from 'react-router-dom';
import { useReportByToken } from '../hooks/use-reports';
import { Download, AlertCircle, Loader2 } from 'lucide-react';
import { formatDate } from '../lib/utils';

export function GuestReportPage() {
  const { token } = useParams<{ token: string }>();
  const { data: report, isLoading, error } = useReportByToken(token || '');

  const handleDownload = () => {
    if (report) {
      window.open(report.pdf_url, '_blank');
    }
  };

  if (isLoading) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-slate-50">
        <div className="text-center">
          <Loader2 className="h-12 w-12 text-indigo-600 animate-spin mx-auto mb-4" />
          <p className="text-slate-600">Loading report...</p>
        </div>
      </div>
    );
  }

  if (error || !report) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-slate-50 p-4">
        <div className="max-w-md w-full bg-white rounded-xl border border-slate-200 p-8 text-center">
          <AlertCircle className="h-16 w-16 text-red-500 mx-auto mb-4" />
          <h2 className="text-2xl font-bold text-slate-900 mb-2">
            Report Not Found
          </h2>
          <p className="text-slate-600 mb-6">
            This report link may have expired or is invalid. Please request a new
            share link from the report owner.
          </p>
          <a
            href="/"
            className="inline-flex items-center justify-center px-6 py-3 bg-indigo-600 text-white rounded-lg font-medium hover:bg-indigo-700 transition-colors"
          >
            Go to Login
          </a>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-slate-50">
      {/* Header */}
      <div className="bg-white border-b border-slate-200">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-6">
          <div className="flex items-center justify-between">
            <div>
              <h1 className="text-2xl font-bold text-slate-900">
                JABB <span className="text-indigo-600">Business</span> Flash Report
              </h1>
              <p className="mt-1 text-sm text-slate-600">
                Shared Report • Generated {formatDate(report.created_at)}
              </p>
            </div>
            <button
              onClick={handleDownload}
              className="flex items-center gap-2 px-6 py-3 bg-indigo-600 text-white rounded-lg font-medium hover:bg-indigo-700 transition-colors"
            >
              <Download className="h-5 w-5" />
              Download PDF
            </button>
          </div>
        </div>
      </div>

      {/* Report Details */}
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        <div className="grid grid-cols-1 md:grid-cols-4 gap-6 mb-8">
          <div className="bg-white rounded-xl border border-slate-200 p-6">
            <p className="text-sm text-slate-600 mb-1">Quick JABBs</p>
            <p className="text-3xl font-bold text-slate-900">
              {report.metadata.jabbs_count}
            </p>
          </div>
          <div className="bg-white rounded-xl border border-slate-200 p-6">
            <p className="text-sm text-slate-600 mb-1">Overall Score</p>
            <p className="text-3xl font-bold text-indigo-600">
              {report.metadata.score_percentage}%
            </p>
          </div>
          <div className="bg-white rounded-xl border border-slate-200 p-6">
            <p className="text-sm text-slate-600 mb-1">UP Rate</p>
            <p className="text-3xl font-bold text-green-600">
              {(report.metadata.up_rate * 100).toFixed(0)}%
            </p>
          </div>
          <div className="bg-white rounded-xl border border-slate-200 p-6">
            <p className="text-sm text-slate-600 mb-1">DOWN Rate</p>
            <p className="text-3xl font-bold text-red-600">
              {(report.metadata.down_rate * 100).toFixed(0)}%
            </p>
          </div>
        </div>

        {/* PDF Embed */}
        <div className="bg-white rounded-xl border border-slate-200 overflow-hidden">
          <div className="aspect-[8.5/11] w-full">
            <iframe
              src={report.pdf_url}
              className="w-full h-full"
              title="Flash Report PDF"
            />
          </div>
        </div>

        {/* Footer Info */}
        <div className="mt-8 text-center">
          <p className="text-sm text-slate-500">
            This report link expires on {new Date(report.expires_at).toLocaleDateString()}
          </p>
          <p className="mt-2 text-xs text-slate-400">
            Generated by JABB Business Analytics Platform
          </p>
        </div>
      </div>
    </div>
  );
}
